<?php

namespace Database\Seeders;

use App\Models\Tour;
use Illuminate\Database\Seeder;

class TourSeeder extends Seeder
{
    public function run(): void
    {
        $tours = [
            [
                'name' => 'Borobudur Sunrise Tour',
                'slug' => 'borobudur-sunrise-tour',
                'description' => 'Enjoy the magnificent sunrise view at Borobudur Temple. This tour takes you to witness the spectacular blend of history, architecture, and morning landscape of Central Java.',
                'short_description' => 'Witness the magical sunrise over the magnificent Borobudur Temple.',
                'image' => 'template/assets/images/travel-list/1.jpg',
                'price' => 350000,
                'discount_price' => 275000,
                'duration_info' => 'Full Day (12 Hours)',
                'category' => 'Cultural',
                'tag' => 'Bestseller',
                'rating' => 4.9,
                'review_count' => 128,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Prambanan Temple Tour',
                'slug' => 'prambanan-temple-tour',
                'description' => 'Explore the majestic Prambanan Temple, the largest and most beautiful Hindu temple complex in Indonesia.',
                'short_description' => 'Visit the largest and grandest Hindu temple complex in Indonesia.',
                'image' => 'template/assets/images/travel-list/2.jpg',
                'price' => 250000,
                'discount_price' => 200000,
                'duration_info' => 'Full Day (10 Hours)',
                'category' => 'Cultural',
                'tag' => 'Popular',
                'rating' => 4.8,
                'review_count' => 95,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Jomblang Cave Adventure',
                'slug' => 'jomblang-cave-adventure',
                'description' => 'An exciting adventure down into Jomblang Cave using vertical caving techniques. Witness the famous "Light of Heaven" sunbeams.',
                'short_description' => 'Exciting vertical caving adventure to see the magnificent sunbeams.',
                'image' => 'template/assets/images/travel-list/3.jpg',
                'price' => 450000,
                'discount_price' => 375000,
                'duration_info' => 'Full Day (11 Hours)',
                'category' => 'Adventure',
                'tag' => 'Trending',
                'rating' => 4.7,
                'review_count' => 76,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Parangtritis Beach Tour',
                'slug' => 'parangtritis-beach-tour',
                'description' => 'Enjoy the unique atmosphere and exotic black sand of Parangtritis Beach along with its mystical local folklore.',
                'short_description' => 'Explore the exotic black volcanic sand beach with a spectacular sunset view.',
                'image' => 'template/assets/images/travel-list/4.jpg',
                'price' => 200000,
                'discount_price' => 150000,
                'duration_info' => 'Half Day (6 Hours)',
                'category' => 'Nature',
                'tag' => 'Hot Deal',
                'rating' => 4.6,
                'review_count' => 112,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Malioboro City Tour',
                'slug' => 'malioboro-city-tour',
                'description' => 'Explore the lively heart of Yogyakarta at Malioboro Street. Shop for authentic local crafts and enjoy traditional food.',
                'short_description' => 'Explore the iconic main street and shopping hub of Yogyakarta.',
                'image' => 'template/assets/images/travel-list/5.jpg',
                'price' => 150000,
                'discount_price' => 100000,
                'duration_info' => 'Half Day (5 Hours)',
                'category' => 'City Tour',
                'tag' => 'Bestseller',
                'rating' => 4.5,
                'review_count' => 203,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Kidul Mountain Tour',
                'slug' => 'kidul-mountain-tour',
                'description' => 'An adventure to the pristine white sand beaches of Southern Gunung Kidul, featuring beautiful limestone cliffs.',
                'short_description' => 'Discover the scenic coastline and white sand beaches of Gunung Kidul.',
                'image' => 'template/assets/images/travel-list/6.jpg',
                'price' => 300000,
                'discount_price' => 250000,
                'duration_info' => '2 Days 1 Night',
                'category' => 'Nature',
                'tag' => 'Adventure',
                'rating' => 4.7,
                'review_count' => 89,
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Imogiri Royal Cemetery Tour',
                'slug' => 'imogiri-royal-cemetery-tour',
                'description' => 'Visit the historic Mataram Royal Cemetery at Imogiri hills and learn about Javanese cultural heritage and royal lineage.',
                'short_description' => 'A heritage trip to the sacred royal cemetery of Mataram kings.',
                'image' => 'template/assets/images/travel-list/7.jpg',
                'price' => 175000,
                'discount_price' => 125000,
                'duration_info' => 'Half Day (4 Hours)',
                'category' => 'Cultural',
                'tag' => 'Heritage',
                'rating' => 4.4,
                'review_count' => 67,
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Pindul Cave Tubing',
                'slug' => 'pindul-cave-tubing',
                'description' => 'Enjoy the unique sensation of floating down an underground river inside Pindul Cave on an inflated inner tube.',
                'short_description' => 'Fun and exciting cave tubing adventure in a subterranean river.',
                'image' => 'template/assets/images/travel-list/8.jpg',
                'price' => 200000,
                'discount_price' => 150000,
                'duration_info' => 'Half Day (5 Hours)',
                'category' => 'Adventure',
                'tag' => 'Fun',
                'rating' => 4.6,
                'review_count' => 145,
                'is_featured' => false,
                'is_active' => true,
            ],
        ];

        foreach ($tours as $tour) {
            Tour::create($tour);
        }
    }
}
